### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by AlexTheOutsider22** [lptstr/winfetch#176]
how can I run winfetch at Terminal startup? I cant remember how to do it

**Comment by rashil2000** [comment]
Run this:
```pwsh
New-Item $PROFILE -Force
Add-Content $PROFILE winfetch
```

Now it will run every time you start PowerShell.

**Comment by liams000** [comment]
> Run this:
> 
> New-Item $PROFILE -Force
> Add-Content $PROFILE winfetch
> 
> Now it will run every time you start PowerShell.

Be aware before running this command, **_this will completely wipe your current profile configuration_**. Instead, open the file in a text editor and add `winfetch` somewhere in the file.

To find the file, run 
```
explorer $profile
```
This will open the containing folder in the file explorer, you can then open the file with a text editor and add `winfetch` somewhere to this file.

If you already ran the above command like me, don't stress and don't close your current shell session or reload the session. We can recover it! Run the below commands to recover your current session functions like a pro!

```sh
# Create a backup file with timestamp
$backupFile = "$((Split-Path $PROFILE))\Profile_Backup_$(Get-Date -Format 'yyyyMMdd_HHmmss').ps1"

# Start the backup file
"# PowerShell Profile Backup - $(Get-Date)" | Out-File $backupFile

# Get all functions (exclude built-in ones)
"# Functions" | Out-File $backupFile -Append
Get-ChildItem Function: | Where-Object { -not $_.Options.HasFlag([System.Management.Automation.ScopedItemOptions]::AllScope) -and -not $_.Options.HasFlag([System.Management.Automation.ScopedItemOptions]::ReadOnly) } | ForEach-Object {
    "function $($_.Name) {`n$($_.Definition)`n}" | Out-File $backupFile -Append
}

# Get all aliases (exclude built-in ones)
"# Aliases" | Out-File $backupFile -Append
Get-Alias | Where-Object { -not $_.Options.HasFlag([System.Management.Automation.ScopedItemOptions]::AllScope) -and -not $_.Options.HasFlag([System.Management.Automation.ScopedItemOptions]::ReadOnly) } | ForEach-Object {
    "Set-Alias -Name $($_.Name) -Value $($_.Definition)" | Out-File $backupFile -Append
}

# Get PSReadLine settings if you have them
"# PSReadLine Settings" | Out-File $backupFile -Append
Get-PSReadLineOption | Out-File $backupFile -Append

# Show the backup file location
Write-Host "Backup saved to: $backupFile" -ForegroundColor Green
```

Then clean up the file because there will be a few things in there that you didn't add yourself. 

You're welcome, you successfully recovered your PowerShell profile.

View my github if you want a solution that boots up faster than this one btw.
