### ISSUE TITLE
Problem running the script

### ISSUE THREAD

**Issue by Netris89** [lptstr/winfetch#68]
Hi,

I installed Winfetch using scoop, but every time I try to run it, it displays the following errors (sorry for the french).

![image](https://user-images.githubusercontent.com/56936747/110858747-be1c8480-82ba-11eb-8037-791f921eb926.png)

It works perfectly when I execute it directly without saving the file to disk.
What did I do wrong and how can I fix it ?

Thanks in advance.

**Comment by jcwillox** [comment]
Yeah sorry, this was an issue with the older version of WinFetch see #41, this is fixed in the latest version (v2.0.0), however, we're still waiting on lukesampson/scoop-extras#5678 for that version to be released on scoop. Scoops currently stuck on v1.3.0. So, for now I'd recommend temporarily using one of the other [installation methods](https://github.com/lptstr/winfetch/wiki/Installation).

**Comment by Netris89** [comment]
Alright, thank you for the fast answer.

**Comment by rashil2000** [comment]
Fixed.
